Update bitnami-pkg

diff --git a/5/debian-10/prebuildfs/usr/sbin/bitnami-pkg b/5/debian-10/prebuildfs/usr/sbin/bitnami-pkg
--- a/5/debian-10/prebuildfs/usr/sbin/bitnami-pkg
+++ b/5/debian-10/prebuildfs/usr/sbin/bitnami-pkg
@@ -152,22 +152,22 @@ else
   else
     CURL_ARGS="-sS"
   fi
-  if ! curl $CURL_ARGS -LOf "https://downloads.bitnami.com/files/$RELEASE_BUCKET/$PACKAGE.tar.gz"; then
-    warn "Package name '$PACKAGE' does not exist, will try '${PACKAGE%-$(identify_distro)}'..."
-    if curl $CURL_ARGS -LOf "https://downloads.bitnami.com/files/$RELEASE_BUCKET/${PACKAGE%-$(identify_distro)}.tar.gz"; then
-      PACKAGE="${PACKAGE%-$(identify_distro)}"
-    else
-      error "Could not find the requested package..."
-      exit 1
+  if ! [[ $PACKAGE == *"wordpress"* ]]; then
+    if ! curl $CURL_ARGS -LOf "https://downloads.bitnami.com/files/$RELEASE_BUCKET/$PACKAGE.tar.gz"; then
+      warn "Package name '$PACKAGE' does not exist, will try '${PACKAGE%-$(identify_distro)}'..."
+      if curl $CURL_ARGS -LOf "https://downloads.bitnami.com/files/$RELEASE_BUCKET/${PACKAGE%-$(identify_distro)}.tar.gz"; then
+        PACKAGE="${PACKAGE%-$(identify_distro)}"
+      else
+        error "Could not find the requested package..."
+        exit 1
+      fi
     fi
+  else
+    curl $CURL_ARGS -LOf "https://sitebay-downloads.s3-us-west-2.amazonaws.com/$PACKAGE.tar.gz";
   fi
 fi
 
-if [[ $PACKAGE == *"wordpress"* ]]; then
-  echo "Downloading custom WordPress image.."
-  rm -f $PACKAGE.tar.gz
-  curl $CURL_ARGS -LOf "https://sitebay-downloads.s3-us-west-2.amazonaws.com/$PACKAGE.tar.gz";
-fi
+
 
 if ! tar tzf $PACKAGE.tar.gz >/dev/null 2>&1; then
   error "Invalid or corrupt '$PACKAGE' package."
